Update Assembly_Guide.md
VoronDesign/Voron-Hardware pull request #54
Opened 2020-12-01 11:07 UTC by Pixeltrace-GER

Fixed Link to Setup guide

2020-12-11 23:47 UTC, raymondh2 commented on V0_Display/Software/DisplayButtons.cfg
> +color_order: RGB
`color_order:` should be `GRB`

2020-12-11 23:47 UTC, raymondh2 commented on V0_Display/Software/DisplayEncoder.cfg
> +color_order: RGB
`color_order:` should be `GRB`

2020-12-11 23:47 UTC, raymondh2 requested changes
`color_order:` should be `GRB`

2020-12-12 04:27 UTC, Pixeltrace-GER commented
Oh, my bad. Changed it.

2020-12-18 03:55 UTC, raymondh2 commented
Merged in #57

2020-12-18 03:55 UTC, closed without merging