Update Setup_and_Flashing_Guide.md
VoronDesign/Voron-Hardware pull request #82
Opened 2021-05-26 15:24 UTC by timmit99

Simplification now that there's no display button version.

2021-05-26 15:24 UTC, timmit99 commented
@KiloQubit can you approve this?

2021-05-26 21:43 UTC, KiloQubit requested changes

2021-05-26 21:43 UTC, KiloQubit commented on V0_Display/Documentation/Setup_and_Flashing_Guide.md
> +Best optioon is to copy the config file into the same directory as `printer.cfg` then add `[include DisplayEncoder.cfg]` to the end of your `printer.cfg` to include the file.
s/optioon/option/

2021-05-27 01:32 UTC, KiloQubit approved these changes

2021-05-27 14:25 UTC, timmit99 commented
> @KiloQubit can you approve this?

2021-05-27 15:03 UTC, KiloQubit commented
> @KiloQubit can you approve this?

I already did last night.  I have no powers here, no write access to this repo.

2021-05-27 16:00 UTC, timmit99 commented
@john-- HALP

2021-05-27 19:55 UTC, raymondh2 approved these changes

2021-05-27 19:55 UTC, merged