V0 Umbilical
VoronDesign/Voron-Hardware pull request #97
Opened 2021-10-05 04:38 UTC by timmit99

Addition of the V0 Umbilical PCB's and instructions.

2021-10-05 04:39 UTC, timmit99 commented
I'd like some spellcheck and review of the main readme for any information that could be added/adjusted.

2021-10-07 22:54 UTC, pfmooney reviewed
Thanks for putting this together.  I spotted a few copy-edit nits in the README.

You previously mentioned potentially including a graphic to help folks with the 1:1 pinning of the cable.  Do you plan to skip that, or perhaps include it in a later follow-up?

2021-10-07 22:54 UTC, pfmooney commented on V0-Umbilical/README.md
> +This mod adds two PCB's ([Frame PCB](#frame-pcb), [Toolhead PCB](#toolhead-pcb)) and a cable ([Umbilical Cable](#umbilical-cable)) to the V0.1 that can aid in wire management and routing as well as m
Should be "PCBs" instead of "PCB's" (plural, rather than possessive or a contraction)

2021-10-07 22:54 UTC, pfmooney commented on V0-Umbilical/README.md
> +The frame PCB mounts between the A/B motors at the back of the printer and condenses the heater, thermistor, part cooling fan, hotend cooling fan, extruder motor and the X-endstop into a single 14 pi
nit: perhaps capitalize Micro-Fit

2021-10-07 22:54 UTC, pfmooney commented on V0-Umbilical/README.md
> +Mounting on the toolhead, this breaks out the 14 pin harness into all needed connectors (including a second part fan conenctor so the user doesnt have to spice both fans together)
"doesnt" -> "doesn't"

2021-11-16 00:58 UTC, KiloQubit requested changes
You have STLs for toolhead spacers in `STLs/` and then 10 degree ones in `CAD/Toolhead_PCB/`, which ones is the user supposed to print?

No support for hotend fans with a tach?

2021-11-16 00:58 UTC, KiloQubit commented on README.md
> +| Voron 0 Umbilical   | Set of two PCB's for use with the V0.1 to make witring easier and more modular      |
No apostrophe for plural `PCBs`

Replace `witring` with `wiring`

2021-11-16 00:58 UTC, KiloQubit commented on V0-Umbilical/Images/README.md
> +Yep
Delete this README.

2021-11-17 05:16 UTC, timmit99 commented
> You have STLs for toolhead spacers in `STLs/` and then 10 degree ones in `CAD/Toolhead_PCB/`, which ones is the user supposed to print?
> 
> No support for hotend fans with a tach?

No support for Tach at the moment, wasn't a thing when i was designing. Already thinking of ways to implement this.

2021-11-17 12:33 UTC, KiloQubit approved these changes

2021-11-17 12:33 UTC, merged